version: "3.9"
services:
  media-server:
    container_name: media-server
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - media-server

networks:
  media-server:
    driver: bridge
    name: media-server
