filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/app/*.json
    json.keys_under_root: true
    json.message_key: message
    parsers:
      - ndjson:
          target: ""
          add_error_key: true
    fields:
      log_type: "app-logs" # Add a custom field to identify this log source
    index: "app-logs" # Define the index pattern for this log source

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: true

setup.template.settings:
  index.number_of_shards: 1
  index.number_of_replicas: 0

setup.kibana:
  host: "kibana:5601"

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: "elastic"
  password: "elasticdemo"
